
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class CPass extends javax.swing.JFrame {

    /**
     * Creates new form CPass
     */
    public CPass() {
        initComponents();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/coffer","root","xyz"); 
            Statement stmt3 = (Statement) con.createStatement();
                        String query3="select User from login order by id desc limit 1";
                        ResultSet rs3 = stmt3.executeQuery(query3);
                        
                if(rs3.next())
                {
                    
                String Name = rs3.getString("User");
                JT9.setText(Name);
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        L9 = new javax.swing.JLabel();
        JT9 = new javax.swing.JTextField();
        L10 = new javax.swing.JLabel();
        JT10 = new javax.swing.JTextField();
        B4 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Password");

        L9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        L9.setText("Uid");

        JT9.setEditable(false);
        JT9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        L10.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        L10.setText("Password");

        JT10.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        B4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B4.setText("Confirm");
        B4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 204))));
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B1.setText("Back");
        B1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 204))));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L9, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JT10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L9)
                    .addComponent(JT9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L10)
                    .addComponent(JT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B4)
                    .addComponent(B1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed

        
        String Pwd= JT10.getText();
       
            int p= JOptionPane.showConfirmDialog(this,"Are you sure?","Confirm",JOptionPane.YES_NO_OPTION);
            if (p == JOptionPane.YES_OPTION)
            {

                try
                {
                    Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/coffer","root","xyz"); 
            Statement stmt3 = (Statement) con.createStatement();
                        String query3="select User from login order by id desc limit 1";
                        ResultSet rs3 = stmt3.executeQuery(query3);
                        
                if(rs3.next())
                {
                    
                String Name = rs3.getString("User");
                
                
                    Statement stmt = (Statement) con.createStatement();
                    String query="update users set Pwd='"+Pwd+"' where Uid='"+Name+"';";
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(this,"Password Changed");
                }
                    

                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                }
            }
        
    }//GEN-LAST:event_B4ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        int p= JOptionPane.showConfirmDialog(this,"Are you sure?","Back to Admin Panel?",JOptionPane.YES_NO_OPTION);
        if (p == JOptionPane.YES_OPTION)
        {
            
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/coffer","root","xyz");
                        Statement stmt3 = (Statement) con.createStatement();
                        String query3="select User from login order by id desc limit 1";
                        ResultSet rs3 = stmt3.executeQuery(query3);
                        
                if(rs3.next())
                {
                    
                    String User = rs3.getString("User");                    
                    
                    //Inserting Login details
                    Statement stmt2 = (Statement) con.createStatement();
                    String query2="select Type from users where Uid='"+User+"';";
                    ResultSet rs2 = stmt2.executeQuery(query2);
                    
                    if(rs2.next())
                {
                    String Type = rs2.getString("Type");
                    String adm = "admin";
                    if(Type.equals(adm))
                    {
                    this.setVisible(false);
                    adm s = new adm();
                    s.setVisible(true);
                    }
                    else
                        {
                        this.setVisible(false);
                        emp s = new emp();
                        s.setVisible(true);
                        }
                }
                    //next frame
                    
                    //new One(Name).setVisible(true);
                }
                    
                    }
                
                    
            
            
        
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        }

    }//GEN-LAST:event_B1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B4;
    private javax.swing.JTextField JT10;
    private javax.swing.JTextField JT9;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
