
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class ECr extends javax.swing.JFrame {

    /**
     * Creates new form ECriteria
     */
    public ECr() {
        this.setResizable(false);        
        initComponents();
        //this.setSize(471,503);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGrp1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JT1 = new javax.swing.JTextField();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        JT2 = new javax.swing.JTextField();
        L3 = new javax.swing.JLabel();
        JT3 = new javax.swing.JTextField();
        L4 = new javax.swing.JLabel();
        JT4 = new javax.swing.JTextField();
        B2 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        L7 = new javax.swing.JLabel();
        JT7 = new javax.swing.JTextField();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Criteria");

        JT1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        L1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        L1.setText("Base Salary");

        L2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        L2.setText("Tax Cut (%)");

        JT2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        L3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        L3.setText("Increment (%)");

        JT3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        L4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        L4.setText("Bonus");

        JT4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        B2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B2.setText("Confirm");
        B2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 204))));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B1.setText("Back");
        B1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 204))));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BGrp1.add(RB1);
        RB1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        RB1.setText("Grade A");

        BGrp1.add(RB2);
        RB2.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        RB2.setText("Grade B");

        BGrp1.add(RB3);
        RB3.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        RB3.setText("Grade C");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RB1)
                .addGap(18, 18, 18)
                .addComponent(RB2)
                .addGap(18, 18, 18)
                .addComponent(RB3)
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB2)
                    .addComponent(RB1)
                    .addComponent(RB3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        L7.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        L7.setText("Salary");

        JT7.setEditable(false);
        JT7.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        JT7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JT7CaretUpdate(evt);
            }
        });
        JT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT7ActionPerformed(evt);
            }
        });

        B3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B3.setText("Default");
        B3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 204))));
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B4.setText("Previous");
        B4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 204))));
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B5.setText("Calculate");
        B5.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 204))));
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(L7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JT7, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(L2)
                                .addComponent(L3)
                                .addComponent(L1)
                                .addComponent(L4))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JT4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JT3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JT1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B3)
                    .addComponent(B4))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L1)
                    .addComponent(JT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L2)
                    .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L3)
                    .addComponent(JT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L4)
                    .addComponent(JT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L7)
                    .addComponent(JT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B5)
                    .addComponent(B2))
                .addGap(33, 33, 33)
                .addComponent(B1)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        String bs = JT1.getText();
        String txc = JT2.getText();
        String inc = JT3.getText();
        String bonus = JT4.getText();
       
        int p= JOptionPane.showConfirmDialog(this,"Are you sure?","Confirm",JOptionPane.YES_NO_OPTION);
        if (p == JOptionPane.YES_OPTION)
        {
            
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/coffer","root","xyz");
            Statement stmt = (Statement) con.createStatement();
            String Grade = "";
            if(RB1.isSelected())
             Grade="A";
            else if(RB2.isSelected())
             Grade="B";
            else if(RB3.isSelected())
             Grade="C";
            String query="delete from ecr where Grade='"+Grade+"';";
            stmt.executeUpdate(query);
            Statement stmt2 = (Statement) con.createStatement();
            String query2="insert into ecr values ('"+Grade+"','"+bs+"','"+txc+"','"+inc+"','"+bonus+"');";
            stmt2.executeUpdate(query2);
            //JOptionPane.showMessageDialog(this,"Successfully Deleted");
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    }//GEN-LAST:event_B2ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        int p= JOptionPane.showConfirmDialog(this,"Are you sure?","Back to Admin Panel?",JOptionPane.YES_NO_OPTION);
        if (p == JOptionPane.YES_OPTION)
        {
        this.setVisible(false);
        adm s = new adm();
        s.setVisible(true);
        }
        
    }//GEN-LAST:event_B1ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        /*
        String Grade;
        if(RB1.isSelected())
            Grade="A";
        if(RB1.isSelected())
            Grade="B";
        if(RB1.isSelected())
            Grade="C";
        */
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
            DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/coffer","root","xyz");
            Statement stmt = (Statement) con.createStatement();
            String Grade = "";
            if(RB1.isSelected())
             Grade="A";
            else if(RB2.isSelected())
             Grade="B";
            else if(RB3.isSelected())
             Grade="C";
            String query="select BSry,txct,inc,Bonus from decr where Grade='"+Grade+"';";
            ResultSet rs= stmt.executeQuery(query);
            if(rs.next())
            {
                String bs = rs.getString("BSry");
                String txc = rs.getString("txct");
                String inc = rs.getString("inc");
                String bonus = rs.getString("Bonus");
                float bs2 = Float.parseFloat(bs);
                float txc2 = Float.parseFloat(txc);
                float inc2 = Float.parseFloat(inc);
                float bonus2 = Float.parseFloat(bonus);
                JT1.setText("" + bs2);
                JT2.setText("" + txc2);
                JT3.setText("" + inc2);
                JT4.setText("" + bonus2);
                
                float salary;                
                salary = bs2 - (txc2/100)*bs2 + (inc2/100)*bs2 + bonus2;
                JT7.setText("" + salary);
                
                
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
            DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/coffer","root","xyz");
            Statement stmt = (Statement) con.createStatement();
            String Grade = "";
            if(RB1.isSelected())
             Grade="A";
            else if(RB2.isSelected())
             Grade="B";
            else if(RB3.isSelected())
             Grade="C";
            String query="select BSry,txct,inc,Bonus from ecr where Grade='"+Grade+"';";
            ResultSet rs= stmt.executeQuery(query);
            if(rs.next())
            {
                String bs = rs.getString("BSry");
                String txc = rs.getString("txct");
                String inc = rs.getString("inc");
                String bonus = rs.getString("Bonus");
                float bs2 = Float.parseFloat(bs);
                float txc2 = Float.parseFloat(txc);
                float inc2 = Float.parseFloat(inc);
                float bonus2 = Float.parseFloat(bonus);
                JT1.setText("" + bs2);
                JT2.setText("" + txc2);
                JT3.setText("" + inc2);
                JT4.setText("" + bonus2);
                
                float salary;                
                salary = bs2 - (txc2/100)*bs2 + (inc2/100)*bs2 + bonus2;
                JT7.setText("" + salary);
                
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_B4ActionPerformed

    private void JT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT7ActionPerformed

    private void JT7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JT7CaretUpdate
        /*
        int bs =Integer.parseInt(JT1.getText()); 
        int txc =Integer.parseInt(JT2.getText()); 
        int inc =Integer.parseInt(JT3.getText()); 
        int bonus =Integer.parseInt(JT4.getText());
        int salary;
        salary = bs - (txc/100)*bs + (inc/100)*bs + bonus;
        JT7.setText("" + salary);
        */
        
    }//GEN-LAST:event_JT7CaretUpdate

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        
        
        float bs5 =Float.parseFloat(JT1.getText()); 
        float txc5 =Float.parseFloat(JT2.getText()); 
        float inc5 =Float.parseFloat(JT3.getText()); 
        float bonus5 =Float.parseFloat(JT4.getText());
        
        float salary;
        salary = bs5 - (txc5/100)*bs5 + (inc5/100)*bs5 + bonus5;
        JT7.setText("" + salary);
    }//GEN-LAST:event_B5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ECr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ECr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ECr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ECr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ECr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.ButtonGroup BGrp1;
    private javax.swing.JTextField JT1;
    private javax.swing.JTextField JT2;
    private javax.swing.JTextField JT3;
    private javax.swing.JTextField JT4;
    private javax.swing.JTextField JT7;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L7;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
